### ISSUE TITLE
This project when used with CodePipeline construct and github source fails at synthesize step

### ISSUE THREAD

**Issue by ishanjain28** [fongie/webhook-filtered-pipeline#8]
The new `CodePipeline` construct which is supposed to be used in place of now deprecated `CdkPipeline` is used like this,

```ts

   const webhookPipeline = new WebhookFilteredPipeline(
      this,
      "CDKWebhookPipeline",
      {
        githubSourceActionProps: {
          ...props.repo,
          actionName: "Pull_Source_Code",
          output: sourceArtifact,
          trigger: GitHubTrigger.WEBHOOK,
          oauthToken: oauthToken,
        },
        restartExecutionOnUpdate: true,
        webhookFilters: [
// Filters
        ],
      }
    );

  const pipeline = new CodePipeline(this, 'CDKPipeline', {
      codePipeline: webhookPipeline,
      synth: new ShellStep('Synth', {
        input: CodePipelineSource.gitHub(
          `${props.repo.owner}/${props.repo.repo}`,
          props.repo.branch,
          {
            authentication: oauthToken,
            trigger: GitHubTrigger.NONE,
          },
        ),
        commands: [
          'yarn install --immutable --immutable-cache --check-cache',
          'npm run build',
          'npx cdk synth',
        ],
        primaryOutputDirectory: 'cdk.out',
      }),
    });
```

In `CodePipeline`, `input` is a required field.

This project here, https://github.com/fongie/webhook-filtered-pipeline/blob/d4dd69031861158f7febcd5ae0b37405b8795b9c/src/index.ts#L87 adds it's own source action if we are using Github which causes errors in deploying the CDK project because there are now 2 source steps. 

I have tested removing the line that adds source action to the pipeline and it works fine after that.

**Comment by fongie** [comment]
Hi @ishanjain28 thanks for opening an issue! You're right that I haven't updated this lib in a while, and there are changes in the pipelines (and also v2). If you've already solved this issue, would you like to open a PR? Otherwise, I will look into it when I have time
